spring:
  application:
    name: auth-service
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
    database: ${SPRING_DATA_MONGODB_NAME}
server:
  port: ${SERVER_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: "*"