spring:
  application:
    name: auth-service
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
    database: ${SPRING_DATA_MONGODB_NAME}
server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework

security:
  jwt:
    expiration: ${TOKEN_EXPIRATION}
    secret-key: ${TOKEN_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics