services:
  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "${PATIENT_SERVICE_PORT}:${PATIENT_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${PATIENT_SERVICE_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGO_PATIENT_URI}
      SPRING_DATA_MONGODB_NAME: ${PATIENT_DATA_MONGODB_NAME}
volumes:
  patient-db-data:

networks:
  clinic-network:
    driver: bridge