services:
  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${GATEWAY_SERVICE_PORT}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    depends_on:
      discovery-service:
        condition: service_healthy
      patient-service:
        condition: service_started
      doctor-service:
        condition: service_started
      booking-service:
        condition: service_started
      auth-service:
        condition: service_started
    networks:
      - clinic-network

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    container_name: discovery-service
    ports:
      - "${DISCOVERY_SERVICE_PORT}:${DISCOVERY_SERVICE_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${DISCOVERY_SERVICE_PORT}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    networks:
      - clinic-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${DISCOVERY_SERVICE_PORT}/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    container_name: patient-service
    ports:
      - "${PATIENT_SERVICE_PORT}:${PATIENT_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${PATIENT_SERVICE_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_NAME: ${PATIENT_DATA_MONGODB_NAME}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    networks:
      - clinic-network
    depends_on:
      discovery-service:
        condition: service_healthy

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${AUTH_SERVICE_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_NAME: ${AUTH_DATA_MONGODB_NAME}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    networks:
      - clinic-network
    depends_on:
      discovery-service:
        condition: service_healthy

  doctor-service:
    build:
      context: .
      dockerfile: doctor-service/Dockerfile
    container_name: doctor-service
    ports:
      - "${DOCTOR_SERVICE_PORT}:${DOCTOR_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${DOCTOR_SERVICE_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_NAME: ${DOCTOR_DATA_MONGODB_NAME}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    networks:
      - clinic-network
    depends_on:
      discovery-service:
        condition: service_healthy

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking-service
    ports:
      - "${BOOKING_SERVICE_PORT}:${BOOKING_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${BOOKING_SERVICE_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_NAME: ${BOOKING_DATA_MONGODB_NAME}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    networks:
      - clinic-network
    depends_on:
      discovery-service:
        condition: service_healthy

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "${KAFKA_HOST_PORT_1}:${KAFKA_HOST_PORT_1}"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "nZbZ5s5aT4W4o1eX4OEVRA"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge
volumes:
  kafka-data: