services:

  auth-service:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: ${AUTH_SERVICE_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_NAME: ${AUTH_DATA_MONGODB_NAME}
    networks:
      - clinic-network
    depends_on:
      - config-service
      - discovery-service

  patient-service:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    container_name: patient-service
    ports:
      - "${PATIENT_SERVICE_PORT}:${PATIENT_SERVICE_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: ${PATIENT_SERVICE_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_NAME: ${PATIENT_DATA_MONGODB_NAME}
    networks:
      - clinic-network

  doctor-service:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: doctor-service/Dockerfile
    container_name: doctor-service
    ports:
      - "${DOCTOR_SERVICE_PORT}:${DOCTOR_SERVICE_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - clinic-network

  booking-service:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking-service
    ports:
      - "${BOOKING_SERVICE_PORT}:${BOOKING_SERVICE_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - clinic-network

  chat-service:
    build:
      context: .
      dockerfile: chat-service/Dockerfile
    container_name: chat-service
    ports:
      - "${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_NAME: ${CHAT_DATA_MONGODB_NAME}
    depends_on:
      - redis
    networks:
      - clinic-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - clinic-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - clinic-network