spring:
  application:
    name: plane-service
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
    database: ${SPRING_DATA_MONGODB_NAME}
    representation:
      uuid: STANDARD
server:
  port: ${SERVER_PORT}