spring:
  application:
    name: chat-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
    database: ${SPRING_DATA_MONGODB_NAME}

server:
  port: ${SERVER_PORT:8085}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG