<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.clinicapp</groupId>
		<artifactId>clinic-app</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>clinic-module</artifactId>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.8.15</version>
		</dependency>
		<dependency>
			<groupId>com.clinicapp</groupId>
			<artifactId>patient-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.clinicapp</groupId>
			<artifactId>doctor-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.clinicapp</groupId>
			<artifactId>medical-record-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.clinicapp</groupId>
			<artifactId>appointment-module</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
		</dependency>


	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>